" Make external commands work through a pipe instead of a pseudo-tty
"set noguipty

" You can also specify a different font, overriding the default font
"if has('gui_gtk2')
"  set guifont=Bitstream\ Vera\ Sans\ Mono\ 12
"else
"  set guifont=-misc-fixed-medium-r-normal--14-130-75-75-c-70-iso8859-1
"endif

" If you want to run gvim with a dark background, try using a different
" colorscheme or running 'gvim -reverse'.
" http://www.cs.cmu.edu/~maverick/VimColorSchemeTest/ has examples and
" downloads for the colorschemes on vim.org

" Source a global configuration file if available
set nocompatible            " 关闭 vi 兼容模式
filetype plugin indent on   " 开启插件
syntax on                   " 自动语法高亮
colorscheme molokai " 设定配色方案
"set guifont=文泉驿等宽正黑\ Medium\ 11
set guifont=Monaco\ Medium\ 10
"set cursorline              " 突出显示当前行
set shiftwidth=4            " 设定 << 和 >> 命令移动时的宽度为 4
set softtabstop=4           " 使得按退格键时可以一次删掉 4 个空格
set tabstop=4               " 设定 tab 长度为 4
set nobackup                " 覆盖文件时不备份
set autochdir               " 自动切换当前目录为当前文件所在的目录
set backupcopy=yes          " 设置备份时的行为为覆盖
"set ignorecase smartcase    " 搜索时忽略大小写，但在有一个或以上大写字母时仍保持对大小写敏感
set wrapscan		    " 禁止在搜索到文件两端时重新搜索
set incsearch		    " 输入搜索内容时就显示搜索结果
set hlsearch                " 搜索时高亮显示被找到的文本
set noerrorbells            " 关闭错误信息响铃
set novisualbell            " 关闭使用可视响铃代替呼叫
set t_vb=                   " 置空错误铃声的终端代码
" set modelines=5
" set showmatch			    " 插入括号时，短暂地跳转到匹配的对应括号
" set matchtime=2		    " 短暂跳转到匹配括号的时间
set magic			    " 设置魔术
set hidden			    " 允许在有未保存的修改时切换缓冲区，此时的修改由 vim 负责保存
set guioptions-=T		    " 隐藏工具栏
set guioptions-=m		    " 隐藏菜单栏
set guioptions-=r
set smartindent			    " 开启新行时使用智能自动缩进
set backspace=indent,eol,start
				    " 不设定在插入状态无法用退格键和 Delete 键删除回车符
				    " 设置在状态行显示的信息
set foldmethod=manual		    " 设置语法折叠
set foldcolumn=0		    " 设置折叠区域的宽度
setlocal foldlevel=1		    " 设置折叠层数为
"set foldclose=all		    " 设置为自动关闭折叠                            
"nnoremap <space> @=((foldclosed(line('.')) < 0) ? 'zc' : 'zo')<CR>
                            " 用空格键来开关折叠
filetype plugin indent on
filetype on
"
"=================Key bind============================                            
if filereadable("/etc/vim/keybind.vim")
  source /etc/vim/keybind.vim
endif

" return OS type, eg: windows, or linux, mac, et.st..
function! MySys()
    if has("win16") || has("win32") || has("win64") || has("win95")
        return "windows"
    elseif has("unix")
        return "linux"
    endif
endfunction

" 用户目录变量$VIMFILES
if MySys() == "windows"
    let $VIMFILES = $VIM.'/vimfiles'
elseif MySys() == "linux"
    let $VIMFILES = $HOME.'/.vim'
endif

" 设定doc文档目录
let helptags=$VIMFILES.'/doc'

" 设置字体 以及中文支持
if has("win32")
    set guifont=Inconsolata:h12:cANSI
endif



" Buffers操作快捷方式!
nnoremap <C-RETURN> :bnext<CR>
nnoremap <C-S-RETURN> :bprevious<CR>

" Tab操作快捷方式!
nnoremap <C-TAB> :tabnext<CR>
nnoremap <C-S-TAB> :tabprev<CR>

"关于tab的快捷键
" map tn :tabnext<cr>
" map tp :tabprevious<cr>
" map td :tabnew .<cr>
" map te :tabedit
" map tc :tabclose<cr>

"窗口分割时,进行切换的按键热键需要连接两次,比如从下方窗口移动
"光标到上方窗口,需要<c-w><c-w>k,非常麻烦,现在重映射为<c-k>,切换的
"时候会变得非常方便.
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

"设置vim的文件格式"
set fileformats=unix,dos,mac




" 让 Tohtml 产生有 CSS 语法的 html
" syntax/2html.vim，可以用:runtime! syntax/2html.vim
let html_use_css=1


" 选中状态下 Ctrl+c 复制
vmap <leader>c "+y
vmap <leader>p "+p
" IMPORTANT: win32 users will need to have 'shellslash' set so that latex
" can be called correctly.
set shellslash
" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
set grepprg=grep\ -nH\ $*
" OPTIONAL: This enables automatic indentation as you type.
" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
let g:tex_flavor='latex'
"vim 的选项
let g:vimim_mode='dynamic'
"-----------------------------------------------------------------
if filereadable("/etc/vim/gvimrc.local")
  source /etc/vim/gvimrc.local
endif
