scriptencoding utf-8
" ^^ Please leave the above line at the start of the file.

" Default configuration file for Vim
" $Header: /var/cvsroot/gentoo-x86/app-editors/vim-core/files/vimrc-r4,v 1.3 2010/04/15 19:30:32 darkside Exp $

" Written by Aron Griffis <agriffis@gentoo.org>
" Modified by Ryan Phillips <rphillips@gentoo.org>
" Modified some more by Ciaran McCreesh <ciaranm@gentoo.org>
" Added Redhat's vimrc info by Seemant Kulleen <seemant@gentoo.org>

" You can override any of these settings on a global basis via the
" "/etc/vim/vimrc.local" file, and on a per-user basis via "~/.vimrc". You may
" need to create these.

" {{{ General settings
" The following are some sensible defaults for Vim for most users.
" We attempt to change as little as possible from Vim's defaults,
" deviating only where it makes sense
"if ! has("gui_running")
"  set nocompatible      " Use Vim defaults (much better!)
"  filetype plugin indent on
"
"endif  

set nocompatible      " Use Vim defaults (much better!)
set bs=2                " Allow backspacing over everything in insert mode
set ai                  " Always set auto-indenting on
set history=50          " keep 50 lines of command history
set ruler               " Show the cursor position all the time
set number
"set cursorline              " 突出显示当前行
"set ignorecase smartcase    " 搜索时忽略大小写，但在有一个或以上大写字母时仍保持对大小写敏感
set smartindent
set cmdheight=1             " 设定命令行的行数为 1
set laststatus=2            " 显示状态栏 (默认值为 1, 无法显示状态栏)
colorscheme molokai
"set statusline=%<%F[%1*%M%*%n%R%H]\ [%{&fileencoding}]%=%b\ 0x%B\ %y\ %{&fileformat}\ %{&encoding}\ %l,%c%V\ %P
set statusline=%<%F\ \|\ %1*%M%*%n%R%H\ \|\ %{&fileencoding}%=%b\ 0x%B\ %y\ %{&fileformat}\ %{&encoding}\ %l,%c%V\ %P


set foldenable              " 开始折叠
set foldmethod=manual       " 设置语法折叠
set foldcolumn=0            " 设置折叠区域的宽度
setlocal foldlevel=1        " 设置折叠层数为
set viminfo='20,\"500   " Keep a .viminfo file.
set fileformats=unix,dos,mac
set encoding=utf-8
set termencoding=utf-8
set formatoptions+=mM
set nrformats=octal,hex,alpha 
set t_Co=256
filetype plugin indent on
"set foldclose=all           " 设置为自动关闭折叠                            
"nnoremap <leader>f @=((foldclosed(line('.')) < 0) ? 'zc' : 'zo')<CR>
                            " 用空格键来开关折叠
"=================Key bind============================                            
if filereadable("/etc/vim/keybind.vim")
  source /etc/vim/keybind.vim
endif

"=================cscope==========================
set cscopequickfix=s-,c-,d-,i-,t-,e-
set completeopt=longest,menu
"=================cscope==========================
"To start exploring in the current window, use: >
" \be   or   :BufExplorer   or   Your custom key mapping
"To start exploring in a newly split horizontal window, use: >
" \bs   or   :BufExplorerHorizontalSplit   or   Your custom key mapping
"To start exploring in a newly split vertical window, use: >
" \bv   or   :BufExplorerVerticalSplit   or   Your custom key mapping
"=================Bufexplorer==========================
"=================插件设定==========================

  let Tlist_Ctags_Cmd = "/usr/bin/ctags" "指定ctags路径
  let Tlist_Show_One_File = 1  
  let Tlist_Exit_OnlyWindow = 1
  let Tlist_Show_Menu = 1


  let g:miniBufExplMapWindowNavVim = 1
  let g:miniBufExplMapWindowNavArrows = 1
  let g:miniBufExplMapCTabSwitchBufs = 1
  let g:miniBufExplModSelTarget = 1


  let g:neocomplcache_enable_at_startup=1

" vimim 输入法 选项
" let g:vimim_mode='static' "静态输入
" let g:vimim_map='tab_as_onekey' "使用tab键电石成
  let g:vimim_map='c-bslash' 
  let g:vimim_cloud='google'
  let g:vimim_cloud='sogou'
  let g:vimim_map='no-gi'
" let g:vimim_cloud=-1
  let g:vimim_map='c-space'
"set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1,utf-16
"set fileencoding=utf-8
" 配置多语言环境
if has("multi_byte")
    " UTF-8 编码
    set encoding=utf-8
    set termencoding=utf-8
    set formatoptions+=mM
    set fileencodings=utf-8,chinese,gb18030,big5,euc-jp,euc-kr,utf-8,latin1,utf-16

    if v:lang =~? '^\(zh\)\|\(ja\)\|\(ko\)'
        set ambiwidth=double
    endif

    if has("win32")
        source $VIMRUNTIME/delmenu.vim
        source $VIMRUNTIME/menu.vim
        language messages zh_CN.utf-8
    endif

else
    echoerr "Sorry, this version of (g)vim was not compiled with +multi_byte"
endif

" When doing tab completion, give the following files lower priority. You may
" wish to set 'wildignore' to completely ignore files, and 'wildmenu' to enable
" enhanced tab completion. These can be done in the user vimrc file.
set suffixes+=.info,.aux,.log,.dvi,.bbl,.out,.o,.lo

" When displaying line numbers, don't use an annoyingly wide number column. This
" doesn't enable line numbers -- :set number will do that. The value given is a
" minimum width to use for the number column, not a fixed size.
if v:version >= 700
  set numberwidth=3
endif
" }}}

" {{{ Modeline settings
" We don't allow modelines by default. See bug #14088 and bug #73715.
" If you're not concerned about these, you can enable them on a per-user
" basis by adding "set modeline" to your ~/.vimrc file.
set modeline


" {{{ Syntax highlighting settings
" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif
" }}}

" {{{ Terminal fixes
if &term ==? "xterm"
  set t_Sb=^[4%dm
  set t_Sf=^[3%dm
  set ttymouse=xterm2
endif

if &term ==? "gnome" && has("eval")
  " Set useful keys that vim doesn't discover via termcap but are in the
  " builtin xterm termcap. See bug #122562. We use exec to avoid having to
  " include raw escapes in the file.
  exec "set <C-Left>=\eO5D"
  exec "set <C-Right>=\eO5C"
endif
" }}}

" {{{ Filetype plugin settings
" Enable plugin-provided filetype settings, but only if the ftplugin
" directory exists (which it won't on livecds, for example).
" }}}

" {{{ Fix &shell, see bug #101665.
if "" == &shell
  if executable("/bin/bash")
    set shell=/bin/bash
  elseif executable("/bin/sh")
    set shell=/bin/sh
  endif
endif
"}}}

" {{{ Our default /bin/sh is bash, not ksh, so syntax highlighting for .sh
" files should default to bash. See :help sh-syntax and bug #101819.
if has("eval")
  let is_bash=1
endif
" }}}


" {{{ vimrc.local
if filereadable("/etc/vim/vimrc.local") && ! has("gui_running")
  source /etc/vim/vimrc.local
endif

" }}}
" vim: set fenc=utf-8 tw=80 sw=2 sts=2 et  :
